/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenInBlack;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * @author Emil Lager
 * @author Josefin Olsson
 * @author Karin Mäki-Kala
 * @author Veronika Ranta
 */
public class AgentWin extends javax.swing.JFrame {

    private InfDB idb;
    private static String id;

    /**
     * Creates new form AgentWin
     */
    public AgentWin(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;
        visaMinInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        minUtrustningBtn = new javax.swing.JMenuItem();
        visaTopp3AgenterBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        alienBtn = new javax.swing.JMenuItem();
        utrustningBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        omradeBtn = new javax.swing.JMenuItem();
        rasBtn = new javax.swing.JMenuItem();
        periodBtn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        omradesChefBtn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        changePassBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Min information");

        jButton1.setText("Logga ut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Visa ▽");

        minUtrustningBtn.setText("- min utrustning");
        minUtrustningBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minUtrustningBtnActionPerformed(evt);
            }
        });
        jMenu1.add(minUtrustningBtn);

        visaTopp3AgenterBtn.setText("- topp 3 agenter");
        visaTopp3AgenterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaTopp3AgenterBtnActionPerformed(evt);
            }
        });
        jMenu1.add(visaTopp3AgenterBtn);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registrera ▽");

        alienBtn.setText("- alien");
        alienBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienBtnActionPerformed(evt);
            }
        });
        jMenu2.add(alienBtn);

        utrustningBtn.setText("- utrustning");
        utrustningBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utrustningBtnActionPerformed(evt);
            }
        });
        jMenu2.add(utrustningBtn);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Lista alien över ▽");

        omradeBtn.setText("- plats");
        omradeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                omradeBtnActionPerformed(evt);
            }
        });
        jMenu3.add(omradeBtn);

        rasBtn.setText("- ras");
        rasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasBtnActionPerformed(evt);
            }
        });
        jMenu3.add(rasBtn);

        periodBtn.setText("- tidsperiod");
        periodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodBtnActionPerformed(evt);
            }
        });
        jMenu3.add(periodBtn);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sök ▽");

        omradesChefBtn.setText("- områdeschef");
        omradesChefBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                omradesChefBtnActionPerformed(evt);
            }
        });
        jMenu4.add(omradesChefBtn);

        jMenuItem1.setText("- alien");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Inställningar ▽");

        changePassBtn.setText("- ändra lösenord");
        changePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassBtnActionPerformed(evt);
            }
        });
        jMenu5.add(changePassBtn);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void omradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_omradeBtnActionPerformed

        new ListaAliensEfterPlats(idb).setVisible(true);
    }//GEN-LAST:event_omradeBtnActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new ListaAliensEfterDatum(idb).setVisible(true);
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void alienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienBtnActionPerformed
        // TODO add your handling code here:
        new RegAlienWin(idb).setVisible(true);
    }//GEN-LAST:event_alienBtnActionPerformed

    private void utrustningBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utrustningBtnActionPerformed
        // TODO add your handling code here:
        new RegUtrustningWin(idb).setVisible(true);
    }//GEN-LAST:event_utrustningBtnActionPerformed

    private void rasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasBtnActionPerformed
        // TODO add your handling code here:
        new ListaAliensEfterRas(idb).setVisible(true);
    }//GEN-LAST:event_rasBtnActionPerformed

    private void periodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodBtnActionPerformed
        // TODO add your handling code here:
        new ListaAliensEfterDatum(idb).setVisible(true);

    }//GEN-LAST:event_periodBtnActionPerformed

    private void omradesChefBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_omradesChefBtnActionPerformed
        // TODO add your handling code here:
        new SokOmradesChef(idb).setVisible(true);
    }//GEN-LAST:event_omradesChefBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new SokAlien(idb).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void changePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassBtnActionPerformed
        // TODO add your handling code here:
        new AndraLosenAgent(idb, id).setVisible(true);
    }//GEN-LAST:event_changePassBtnActionPerformed

    private void minUtrustningBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minUtrustningBtnActionPerformed
        // TODO add your handling code here:
        new ListaEnAgentsUtrustning(idb, id).setVisible(true);
    }//GEN-LAST:event_minUtrustningBtnActionPerformed

    private void visaTopp3AgenterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaTopp3AgenterBtnActionPerformed
        // TODO add your handling code here:
        new SeTopplistaAgenter(idb).setVisible(true);
    }//GEN-LAST:event_visaTopp3AgenterBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LogInWin(idb).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void visaMinInformation() {

        ArrayList<HashMap<String, String>> valdAgent;

        try {
            String fraga = "SELECT * FROM agent WHERE Agent_ID = " + id;
            valdAgent = idb.fetchRows(fraga);
            System.out.println(id);
            String omradeNamn = idb.fetchSingle("SELECT Benamning FROM omrade WHERE Omrades_ID IN "
                    + "(SELECT Omrade FROM Agent WHERE Agent_ID = " + id + ");");
            for (HashMap<String, String> agent : valdAgent) {
                jTextArea1.append("ID:\t" + agent.get("Agent_ID") + "\n");
                jTextArea1.append("Namn:\t" + agent.get("Namn") + "\n");
                jTextArea1.append("Tel. nr.:\t" + agent.get("Telefon") + "\n");
                jTextArea1.append("Anst. dat.:\t" + agent.get("Anstallningsdatum") + "\n");
                jTextArea1.append("Admin J/N:\t" + agent.get("Administrator") + "\n");
                jTextArea1.append("Område:\t" + omradeNamn);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Kunde inte visa information. \n "
                    + e.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alienBtn;
    private javax.swing.JMenuItem changePassBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem minUtrustningBtn;
    private javax.swing.JMenuItem omradeBtn;
    private javax.swing.JMenuItem omradesChefBtn;
    private javax.swing.JMenuItem periodBtn;
    private javax.swing.JMenuItem rasBtn;
    private javax.swing.JMenuItem utrustningBtn;
    private javax.swing.JMenuItem visaTopp3AgenterBtn;
    // End of variables declaration//GEN-END:variables
}
