/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenInBlack;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * @author Emil Lager
 * @author Josefin Olsson
 * @author Karin Mäki-Kala
 * @author Veronika Ranta
 */

public class AlienWin extends javax.swing.JFrame {
    private InfDB idb;
    private static String id;

    /**
     * Creates new form AgentWin
     */
    public AlienWin(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;
        visaMinInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAndraLosen = new javax.swing.JButton();
        jVisaOchef = new javax.swing.JButton();
        jVisaAliens = new javax.swing.JButton();
        jMejl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAndraLosen.setText("Ändra lösenord");
        jAndraLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAndraLosenActionPerformed(evt);
            }
        });

        jVisaOchef.setText("Visa min områdeschef");
        jVisaOchef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisaOchefActionPerformed(evt);
            }
        });

        jVisaAliens.setText("Visa aliens i mitt område");
        jVisaAliens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisaAliensActionPerformed(evt);
            }
        });

        jMejl.setText("Mejla min områdenschef");
        jMejl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMejlActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Min information");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLogOut.setText("Logga ut");
        jLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jAndraLosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jVisaOchef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jVisaAliens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMejl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jVisaOchef)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jAndraLosen)
                        .addGap(18, 18, 18)
                        .addComponent(jVisaAliens)
                        .addGap(18, 18, 18)
                        .addComponent(jMejl)
                        .addGap(26, 26, 26)
                        .addComponent(jLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(75, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAndraLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAndraLosenActionPerformed
        new AndraLosenAlien(idb,id).setVisible(true);
    }//GEN-LAST:event_jAndraLosenActionPerformed

    private void jVisaOchefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisaOchefActionPerformed
        // TODO add your handling code here:
        new HittaOmradesChef(idb, id).setVisible(true);
    
    
    }//GEN-LAST:event_jVisaOchefActionPerformed

    private void jMejlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMejlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMejlActionPerformed

    private void jVisaAliensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisaAliensActionPerformed
        // TODO add your handling code here:
         new ListaAliensIMittOmrade(idb, id).setVisible(true);
    }//GEN-LAST:event_jVisaAliensActionPerformed

    private void jLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutActionPerformed
        new LogInWin(idb).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLogOutActionPerformed

    private void visaMinInformation() {

        ArrayList<HashMap<String, String>> valdAlien;

        try {
            String fraga = "SELECT * FROM alien WHERE Alien_ID = " + id;
            valdAlien = idb.fetchRows(fraga);
            System.out.println(id);
            String omradeNamn = idb.fetchSingle("SELECT Benamning FROM omrade WHERE Omrades_ID IN "
                    + "(SELECT Omrade FROM Agent WHERE Agent_ID = " + id + ");");
            String ansvarigAgent = idb.fetchSingle("SELECT Namn FROM agent WHERE Agent_ID IN "
                    + "(SELECT Ansvarig_Agent FROM alien WHERE Alien_ID = " + id + ");");
            
            for (HashMap<String, String> alien : valdAlien) {
                jTextArea1.append("ID:\t" + alien.get("Alien_ID") + "\n");
                jTextArea1.append("Namn:\t" + alien.get("Namn") + "\n");
                jTextArea1.append("Tel.nr.:\t" + alien.get("Telefon") + "\n");
                jTextArea1.append("Reg.dat.:\t" + alien.get("Registreringsdatum")+ "\n");
                jTextArea1.append("Område:\t" + omradeNamn + "\n");
                jTextArea1.append("Ansvarig agent:\t" + ansvarigAgent + "\n");
                jTextArea1.append("");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Kunde inte visa information. \n"
                    + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAndraLosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLogOut;
    private javax.swing.JButton jMejl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jVisaAliens;
    private javax.swing.JButton jVisaOchef;
    // End of variables declaration//GEN-END:variables
}
