/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenInBlack;

import javax.swing.JOptionPane;
import oru.inf.InfDB;


/**
 *
 * @author kmaki
 */
public class AndraAdmin extends javax.swing.JFrame {
    private static InfDB idb;

    /**
     * Creates new form AndraAdmin
     */
    public AndraAdmin(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextnamn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabort = new javax.swing.JButton();
        jLaggtill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextnamn.setText("Agent namn");
        jTextnamn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextnamnMousePressed(evt);
            }
        });
        jTextnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnamnActionPerformed(evt);
            }
        });
        getContentPane().add(jTextnamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 112, 113, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ändra en agents administratörstatus");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 19, 220, 87));

        jTabort.setText("Ta bort");
        jTabort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabortMousePressed(evt);
            }
        });
        jTabort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTabortActionPerformed(evt);
            }
        });
        getContentPane().add(jTabort, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 173, 73, -1));

        jLaggtill.setText("Lägg till");
        jLaggtill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLaggtillMousePressed(evt);
            }
        });
        jLaggtill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLaggtillActionPerformed(evt);
            }
        });
        getContentPane().add(jLaggtill, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 173, 73, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnamnActionPerformed

    private void jLaggtillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLaggtillActionPerformed
        // TODO add your handling code here:
        if (Validering.textFaltHarVarde(jTextnamn)){
            String namn = jTextnamn.getText();
        String qJ = "UPDATE AGENT SET ADMINISTRATOR = 'J' WHERE NAMN = '" + namn + "'";
        JOptionPane.showMessageDialog(null, "Agent tillagd som administratör! ");
        }
        else{
            JOptionPane.showMessageDialog(null, "Något gick snett :/! ");
            
        }
        
    }//GEN-LAST:event_jLaggtillActionPerformed

    private void jTabortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTabortActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTabortActionPerformed

    private void jTabortMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabortMousePressed
        // TODO add your handling code here:
        if (Validering.textFaltHarVarde(jTextnamn)){
            String namn = jTextnamn.getText();
        String qN = "UPDATE AGENT SET ADMINISTRATOR = 'N' WHERE NAMN = '" + namn + "'";
        JOptionPane.showMessageDialog(null, "Agent borttagen! ");
        }
                else{
            JOptionPane.showMessageDialog(null, "Något gick snett :/! ");
        }
    }//GEN-LAST:event_jTabortMousePressed

    private void jLaggtillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLaggtillMousePressed
        // TODO add your handling code here:
        if (Validering.textFaltHarVarde(jTextnamn)){
            String namn = jTextnamn.getText();
        String qJ = "UPDATE AGENT SET ADMINISTRATOR = 'J' WHERE NAMN = '" + namn + "'";
        JOptionPane.showMessageDialog(null, "Agent tillagd som administratör! ");
        }
        else{
            JOptionPane.showMessageDialog(null, "Något gick snett :/! ");
            
        }
    }//GEN-LAST:event_jLaggtillMousePressed

    private void jTextnamnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextnamnMousePressed
        // TODO add your handling code here:
        jTextnamn.setText("");
    }//GEN-LAST:event_jTextnamnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndraAdmin(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jLaggtill;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTabort;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextnamn;
    // End of variables declaration//GEN-END:variables
}
