package MenInBlack;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/*
 * @author Emil Lager
 * @author Josefin Olsson
 * @author Karin Mäki-Kala
 * @author Veronika Ranta
 */
public class VisaAliensOmradesChef extends javax.swing.JFrame {

    private static InfDB idb;
    private static String id;

    public VisaAliensOmradesChef(InfDB idb, String id) {
        initComponents();
        this.idb = idb;
        this.id = id;
        visaAgentsInformation();
    }

    private void visaAgentsInformation() {
        try {
            String platsID = idb.fetchSingle("SELECT plats from alien WHERE Alien_ID = " + id);
            String omrade = idb.fetchSingle("SELECT finns_i from plats where Plats_ID =" + platsID);
            String agentID = idb.fetchSingle("SELECT Agent_ID from omradeschef where omrade =" + omrade);
            String agentNamn = idb.fetchSingle("SELECT Namn FROM agent WHERE Agent_ID = " + agentID);
            String agentTelefon = idb.fetchSingle("SELECT Telefon FROM agent WHERE Agent_ID = " + agentID);
            textAreaVisaInfo.setText("Namn: " + agentNamn + "\nTelefon: " + agentTelefon);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kunde inte visa information. \n"
                    + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaVisaInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        bTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaVisaInfo.setColumns(20);
        textAreaVisaInfo.setRows(5);
        jScrollPane1.setViewportView(textAreaVisaInfo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Min områdeschef");

        bTillbaka.setText("Tillbaka");
        bTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(bTillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTillbakaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bTillbakaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaVisaInfo;
    // End of variables declaration//GEN-END:variables
}
